### ISSUE TITLE
consistent API vs REACT_APP_ values

### ISSUE THREAD

**Issue by layik** [layik/eAtlas#122]
- [x] testing strategy
- [x] `REACT_APP_GEOGRAPHY_COLUMN_NAME` -> `REACT_APP_GEOGRAPHY_COLUMN` 
- [x] `REACT_APP_COLUMN_NAME` -> `REACT_APP_COLUMN` 
- [x] `REACT_APP_LAYER_NAME` -> `REACT_APP_LAYER_STYLE`
- [x] remove redundant pattern-match on `props`
  - [x] `import { strict as assert } from 'assert'` and `assert(param != props[paramName])` 
  - [x] replace `param` by `props[paramName]` in `apiValue`
  - [x] delete `param` parameter from `apiValue` and reformat `return` object
  - [x] delete unused pattern-match on `props`
- [x] improve implementation of `boolStr` 
- [x] delete commented `TGVE_API` and associated `export`
- [x] remove README reference to the inconsistency
- <s>check names in `api.R` (and fix typos in comments)</s>
- #129

**Comment by rolyp** [comment]
@layik wrote on Slack:
> Right, should we define what app does before we agree on the merger?
> So far it (app) does:
> A1. template to publish data using tgve on GH pages
> A2. used as remote instance
> A3. used as build workflow of tgver.
> A4. as the only showcase for docs in tgvejs
> A5. as the workflow for developing tgvejs
> A6. not sure if there is more?
>
> What we are trying to add to it:
> B1. notebook documentation?
> B2. full stack template to publish data on own server
> B3. anything else?

B1 goes nicely with A1 & A2, if I ever want to use a notebook with TGVE (which seems likely). So that dispenses with B1. Let's assume B3 is "no", leaving us with B2.

If B2 is a scenario we wish to support (via both R and Python), then I suggest the following:
1. treat them as use cases of app (since it's fine and indeed common for a single app or component to have multiple usage modes)
2. implement two bits of CI, one for R and one for Python, which validate these use cases
Then a user of the app is free to use it "as is" or to adapt the CI for R/Python to host their own data (if I'm understanding what you mean by "full stack" correctly).
